### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by dutch-erik** [Snuffy2/places#54]
Receive following errors and sensor keeps _Initializing..._
```
Logger: homeassistant.helpers.entity
Source: custom_components/places/sensor.py:674
Integration: places ([documentation](https://github.com/Snuffy2/places), [issues](https://github.com/Snuffy2/places/issues))
First occurred: 10:03:06 (131 occurrences)
Last logged: 11:08:05
Update for sensor.location_erik fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 514, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 709, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/places/sensor.py", line 552, in update
    self.do_update("Scan Interval")
  File "/config/custom_components/places/sensor.py", line 674, in do_update
    devicetracker_zone_id = "zone." + devicetracker_zone_id
TypeError: can only concatenate str (not "NoneType") to str
```
```
Logger: homeassistant
Source: custom_components/places/sensor.py:674
Integration: places ([documentation](https://github.com/Snuffy2/places), [issues](https://github.com/Snuffy2/places/issues))
First occurred: 10:02:51 (18 occurrences)
Last logged: 11:00:00
Error doing job: Future exception was never retrieved

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/places/sensor.py", line 547, in tsc_update
    self.do_update("Track State Change")
  File "/config/custom_components/places/sensor.py", line 674, in do_update
    devicetracker_zone_id = "zone." + devicetracker_zone_id
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by Snuffy2** [comment]
Can you turn on debug logging for the integration and post the debugging before this error?

**Comment by Snuffy2** [comment]
Let me know if v1.13.5.4 fixes the issue.

**Comment by dutch-erik** [comment]
Solved. 👍
Thanks.
